### ISSUE TITLE
The top description text is hidden when the browser width > 2800px

### ISSUE THREAD

**Issue by Aha00a** [mandy0529/good-day-minji#1]
The top description text is hidden when the browser width > 2800px

2800px
![image](https://user-images.githubusercontent.com/1396800/168383361-3b05a186-9a9c-4edd-856f-caadae80e385.png)

over 2800px
![image](https://user-images.githubusercontent.com/1396800/168383393-56bc6c4e-fb21-4ccc-a2e5-94c11039cea6.png)

If you don't have a large screen, you can simply reproduce this issue by zoom out action. (`Ctrl`+`Wheel`, or `Ctrl`+`-`)

![image](https://user-images.githubusercontent.com/1396800/168383732-eb4397c9-7b67-4342-ab9b-657032080b51.png)

Sorry, but if you want me to help, I gladly will.

**Comment by minjiground** [comment]
Hello, ahha

Thanks for your effort to mine 😀
I'll give it a try first.
And then if i couldn't , I'll let you know that.

Have a good day !☀️

-----Original Message-----
보낸사람: "KIM, ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>
날짜: 2022. 5. 14 오전 5:27:20
제목: [mandy0529/good-day-minji] The top description text is hidden when the browser width > 2800px (Issue #1)

The top description text is hidden when the browser width > 2800px
2800px
over 2800px
If you don't have a large screen, you can simply reproduce this issue by zoom out action. (Ctrl+Wheel, or Ctrl+-)
Sorry, but if you want me to help, I gladly will.

**Comment by Aha00a** [comment]
https://github.com/mandy0529/good-day-minji/commit/db423054ab32e929464c8e070d5055435a976c3e

I think this issue is fixed.
